//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id_Book { get; set; }
        public string Title { get; set; }
        public Nullable<int> Id_Genre { get; set; }
        public string Author { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Sum_Store { get; set; }
        public Nullable<int> Sum_Warehouse { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
